# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.cache.scope = :box
 
  config.vm.define :node1 do |node|
    node.protect.enabled = true
    node.cache.scope = :box
    node.vm.box = "ubuntu/trusty64"
    node.vm.hostname = "node1"
    #node.vm.network :forwarded_port, guest: 22, host: 2001, id: "ssh"
    node.vm.network :public_network, ip: "192.168.12.20"
    node.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.gui = true
     vb.cpus = "1"
    end    
    node.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y wget curl git
      wget -qO- https://get.docker.com/ | sh
      curl -L https://github.com/docker/compose/releases/download/1.3.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
      chmod +x /usr/local/bin/docker-compose
      git clone https://github.com/sfukazu/docker.git
      git clone https://github.com/gitlabhq/gitlabhq.git
      cd docker/elasticsearch
      docker pull elasticsearch
      docker pull sfukazu/elasticsearch
      docker pull minimum2scp/norikra
      docker pull sfukazu/fluentd_twitter-streaming
      cp /vagrant/fluent.conf /home/vagrant/docker/twitter-streaming/fluentd/fluent.conf
      cd ..
      cd gitlabhq/
      docker-compose up
    SHELL
  end
  config.vm.define :node2 do |node|
    node.cache.scope = :box
    node.vm.box = "ubuntu/trusty64"
    node.vm.hostname = "node2"
    #node.vm.network :forwarded_port, guest: 22, host: 2001, id: "ssh"
    node.vm.network :public_network, ip: "192.168.12.21"
    node.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.gui = true
     vb.cpus = "1"
    end    
    node.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y wget curl git
      wget -qO- https://get.docker.com/ | sh
      git clone https://github.com/sfukazu/docker.git
      cd docker/elasticsearch
      docker pull elasticsearch
      docker pull sfukazu/elasticsearch
    SHELL
  end
  config.vm.define :node3 do |node|
    node.cache.scope = :box
    node.vm.box = "ubuntu/trusty64"
    node.vm.hostname = "node3"
    #node.vm.network :forwarded_port, guest: 22, host: 2001, id: "ssh"
    node.vm.network :public_network, ip: "192.168.12.22"
    node.vm.provider "virtualbox" do |vb|
     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.gui = true
     vb.cpus = "1"
    end    
    node.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y wget curl git
      wget -qO- https://get.docker.com/ | sh
      git clone https://github.com/sfukazu/docker.git
      cd docker/elasticsearch
      docker pull elasticsearch
      docker pull sfukazu/elasticsearch
    SHELL
  end
  
end
